version: '3.8'

services:
  server:
    # build: ./server  <-- Commented out for production usage
    image: ghcr.io/lavizcachamza/trucochampions-server:latest
    container_name: vizcacha-server
    ports:
      - "3011:3001"
    environment:
      - PORT=3001
    env_file:
      - ./server/.env
    # volumes:
    #   - ./server:/app       <-- Not needed if using image
    #   - /app/node_modules

  client:
    # build: ./client
    image: ghcr.io/lavizcachamza/trucochampions-client:latest
    container_name: vizcacha-client
    ports:
      - "8085:5173"
    environment:
      - VITE_API_URL=https://trucochamp.mansaoferta.com.ar/api
    depends_on:
      - server
